# -*- mode: ruby -*-
# vi: set ft=ruby :

boxVersion = "bento/ubuntu-22.04"

proxyGuestName = "proxy"
dbGuestName = "db"
backendGuestName = "backend"

guestsCpus = 2
guestsMemory = 2048

proxyPort = 9080

Vagrant.configure("2") do |config|
  
  config.vm.box = boxVersion
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = guestsMemory
    v.cpus = guestsCpus
  end

  config.vm.provision "update", type: "shell", inline: "apt-get update"
  config.vm.provision "utils", type: "shell", inline: "apt-get install mc -y"
  
  config.vm.define proxyGuestName do |proxy|
    proxy.vm.provider "virtualbox" do |v|
      v.name = proxyGuestName
    end
    proxy.vm.hostname = proxyGuestName
    proxy.vm.network "forwarded_port", guest: 80, host: proxyPort
    proxy.vm.network "private_network", ip: '192.168.100.100', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "100-net"
    proxy.vm.provision "netplan proxy", type: "shell", inline: "cat /vagrant/scripts/netplanProxy.yaml > /etc/netplan/50-vagrant.yaml && netplan apply"
    proxy.vm.provision "install nginx", type: "shell", inline: "apt-get install nginx -y"
    proxy.vm.provision :shell, :path => "./scripts/configureNginx.sh", :name => "configure nginx"

  end

  config.vm.define dbGuestName do |db|
    db.vm.provider "virtualbox" do |v|
      v.name = dbGuestName
    end
    db.vm.hostname = dbGuestName
    db.vm.network "private_network", ip: '192.168.100.101', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "100-net"
    db.vm.network "private_network", ip: '192.168.101.100', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "101-net"
    db.vm.provision "netplan db", type: "shell", inline: "cat /vagrant/scripts/netplanDB.yaml > /etc/netplan/50-vagrant.yaml && netplan apply"
    db.vm.provision "install mysql", type: "shell", inline: "apt-get install mysql-server -y"
    db.vm.provision :shell, :path => "./scripts/createWordPressDB.sh", :name => "create wordpress db"
  end
  
  config.vm.define backendGuestName do |backend|
    backend.vm.provider "virtualbox" do |v|
      v.name = backendGuestName
    end
    backend.vm.hostname = backendGuestName
    backend.vm.network "private_network", ip: '192.168.100.102', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "100-net"
    backend.vm.network "private_network", ip: '192.168.102.100', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "102-net"
    backend.vm.provision "netplan backend", type: "shell", inline: "cat /vagrant/scripts/netplanBackend.yaml > /etc/netplan/50-vagrant.yaml && netplan apply"
    backend.vm.provision "install apache2", type: "shell", inline: "apt-get install apache2 libapache2-mod-php -y"
    backend.vm.provision "install php", type: "shell", inline: "apt-get install php php-mysql php-bcmath php-curl php-imagick php-intl php-json php-mbstring php-mysql php-xml php-zip -y"
    backend.vm.provision :shell, :path => "./scripts/installWordPress.sh", :name => "install wordpress"
    backend.vm.provision :shell, :path => "./scripts/configureApache.sh", :name => "configure apache"
    backend.vm.provision :shell, :path => "./scripts/configureWordPress.sh", :name => "configure wordpress"

  end

end
