---
# tasks file for roles/app

- name: install nginx and additional packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ packages }}"
  become: true
  when: env != "stage"

- name: create environment for services and scripts
  include_tasks: env.yml

- name: copy service files
  copy:
    src: "{{ source_dir }}/{{ item }}"
    dest: /etc/systemd/system
  with_items:
    - "{{ services }}"
    - "{{ daemons }}"
  become: true

- name: copy sripts
  copy:
    src: "{{ source_dir }}/{{ item }}"
    dest: "/home/{{ ansible_user_id }}"
    mode: a+x
  loop: "{{ scripts }}"

- name: create nginx server block configuration for app
  include_tasks: nginx.yml

- name: install app (gunicorn + flask)
  include_tasks: app.yml

- name: enable update service for aws parameter store
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ daemons }}"
  become: true
